spring:
  profiles:
    active: secret

  jpa:
    hibernate:
      ddl-auto: create
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug

server:
  port: 1103

# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: '*'
  allowed-headers: '*'
  max-age: 3600

# 토큰 관련 설정, oauth redirectUri 설정
app:
  tokenSecret: 22E496C90I8NS318135B2431LS83JEH8
  tokenExpiry: 1800000
  refreshTokenExpiry: 604800000
  oAuth2RedirectUris:
    - http://localhost:8080/oauth/redirect

# jwt secret key
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'
