spring:
  profiles:
    active: secret

  jpa:
    hibernate:
      ddl-auto: create
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug

server:
  port: 1103

# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: '*'
  allowed-headers: '*'
  max-age: 3600
